# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EqzHXceCBqr3uZijlEnXlqOxNwOG-2K
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import(classification_report,confusion_matrix)

!pip install -q kagglehub

import kagglehub
data_path=kagglehub.dataset_download( "emmarex/plantdisease")

ex=(".jpg",".png","jpeg")
image_path=[]
for root,dirs,files in os.walk(data_path):
  for file in files:
    if file.lower().endswith(ex):
      image_path.append(os.path.join(root,file))
print(len(image_path))

for i in image_path[:10]:
  print(i)

data=[]
for i in image_path:
  class_name=os.path.basename(os.path.dirname(i))
  data.append((i,class_name))

df=pd.DataFrame(data,columns=["image_path",class_name])

df.head()

df.size

df.nunique()

df["Tomato__Tomato_mosaic_virus"].value_counts()

